#
# This version of the app is deployed to AKS using cd-release-aks
#

image:
  repository: ghcr.io/benc-uk/vuego-demoapp
  pullPolicy: Always

service:
  targetPort: 4000

secretEnv:
  WEATHER_API_KEY:
    secretName: vuego-demoapp
    secretKey: WEATHER_API_KEY
  IPSTACK_API_KEY:
    secretName: vuego-demoapp
    secretKey: IPSTACK_API_KEY
  AUTH_CLIENT_ID:
    secretName: vuego-demoapp
    secretKey: AUTH_CLIENT_ID

ingress:
  enabled: true
  host: vuego-demoapp.kube.benco.io
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  tls:
    enabled: true
    secretName: kube-benco-io-cert
