#
# See this Helm chart for all options
# https://github.com/benc-uk/helm-charts/tree/master/webapp
#

image:
  repository: ghcr.io/benc-uk/vuego-demoapp
  tag: latest
  pullPolicy: Always

service:
  targetPort: 4000
  # Use ClusterIP if you set up ingress
  type: LoadBalancer
#
# Create these secrets if you want to enable optional features, see secrets.sample.sh
#
# secretEnv:
#   WEATHER_API_KEY:
#     secretName: vuego-secrets
#     secretKey: WEATHER_API_KEY
#   AUTH_CLIENT_ID:
#     secretName: vuego-demoapp
#     secretKey: AUTH_CLIENT_ID

#
# If you have an ingress controller set up
#
# ingress:
#   enabled: true
#   host: changeme.example.net
#   tls:
#     enabled: true
#     secretName: changeme-cert-secret
